services:
  backend:
    build: .
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && gunicorn --config gunicorn_config.py website.wsgi:application"
    restart: always
    expose:
      - "8000"
    volumes:
      - ./:/app
      - /var/www/static/:/var/www/static/
    networks:
      - appz-network 

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8990:80"
    volumes:
      - /var/www/static/:/var/www/static/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - appz-network

  networks:
  appz-network:
    driver: bridge 
