# Generated by Django 5.0.3 on 2025-04-12 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=50)),
                ('family_male', models.PositiveIntegerField()),
                ('family_female', models.PositiveIntegerField()),
                ('head_of_family', models.CharField(max_length=100)),
                ('earning_members', models.PositiveIntegerField()),
                ('groceries', models.FloatField()),
                ('recharge', models.FloatField()),
                ('electronics', models.FloatField()),
                ('teaching', models.FloatField()),
                ('stationary', models.FloatField()),
                ('clothing', models.FloatField()),
                ('health', models.FloatField()),
                ('others', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
