# Generated by Django 5.0.3 on 2025-04-12 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='householddata',
            name='mobile_no',
            field=models.CharField(default='exit', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='householddata',
            name='clothing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='householddata',
            name='electronics',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='householddata',
            name='groceries',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='householddata',
            name='health',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='householddata',
            name='others',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='householddata',
            name='recharge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='householddata',
            name='stationary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='householddata',
            name='teaching',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Progress_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('plan_amount', models.FloatField()),
                ('plan_duration', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
