# Generated by Django 5.0.3 on 2025-04-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_householddata_mobile_no_alter_householddata_clothing_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='householddata',
            table='household_data',
        ),
        migrations.AlterModelTable(
            name='progress_report',
            table='progress_report',
        ),
    ]
